# Generated by Django 5.2.3 on 2025-07-02 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True, verbose_name='품번')),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='URLs')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='출시연도')),
                ('rating', models.TextField(blank=True, null=True, verbose_name='평가')),
                ('work_hardness', models.IntegerField(blank=True, null=True, verbose_name='작품 하드함')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/japanese_works/', verbose_name='이미지')),
                ('actors', models.ManyToManyField(blank=True, to='persons.japaneseactor', verbose_name='출연 배우 목록')),
                ('tags', models.ManyToManyField(blank=True, to='core.japaneseworktag', verbose_name='태그 목록')),
            ],
            options={
                'verbose_name': '일본 작품',
                'verbose_name_plural': '일본 작품들',
            },
        ),
        migrations.CreateModel(
            name='KoreanVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None, verbose_name='URLs')),
                ('date', models.DateField(blank=True, null=True, verbose_name='당시 날짜')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos/korean_videos/', verbose_name='이미지')),
                ('edited', models.BooleanField(default=False, verbose_name='편집 여부')),
                ('persons', models.ManyToManyField(blank=True, to='persons.koreanperson', verbose_name='출연 인물 목록')),
                ('tags', models.ManyToManyField(blank=True, to='core.koreanvideotag', verbose_name='태그 목록')),
                ('themes', models.ManyToManyField(blank=True, to='core.koreanvideotheme', verbose_name='주제')),
            ],
            options={
                'verbose_name': '한국 영상',
                'verbose_name_plural': '한국 영상들',
            },
        ),
    ]
