# Generated by Django 5.2.3 on 2025-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreanvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='korean_video_images/', verbose_name='이미지'),
        ),
    ]
