# Generated by Django 5.2.3 on 2025-07-14 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_japaneseactor_name_alter_koreanperson_name'),
        ('videos', '0002_alter_koreanvideo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVideo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='local_videos/', verbose_name='이미지')),
                ('persons', models.ManyToManyField(blank=True, to='persons.koreanperson', verbose_name='인물 목록')),
            ],
            options={
                'verbose_name': '로컬 영상',
                'verbose_name_plural': '로컬 영상들',
                'ordering': ['-uuid'],
            },
        ),
    ]
