# Generated by Django 5.2.3 on 2025-07-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_localvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreanvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/korean_videos/', verbose_name='이미지'),
        ),
    ]
