# Generated by Django 5.2.3 on 2025-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseWorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/japanese_work_tags/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '일본 작품 태그',
                'verbose_name_plural': '일본 작품 태그들',
            },
        ),
        migrations.CreateModel(
            name='KoreanPersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/korean_person_tags/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '한국 인물 태그',
                'verbose_name_plural': '한국 인물 태그들',
            },
        ),
        migrations.CreateModel(
            name='KoreanVideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/korean_video_tags/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '한국 영상 태그',
                'verbose_name_plural': '한국 영상 태그들',
            },
        ),
        migrations.CreateModel(
            name='KoreanVideoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags/korean_video_themes/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '한국 영상 주제',
                'verbose_name_plural': '한국 영상 주제들',
            },
        ),
    ]
