# Generated by Django 5.2.3 on 2025-07-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_japaneseworktag_pumbeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseWorkTagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='유형명')),
            ],
            options={
                'verbose_name': '일본 작품 태그 유형',
                'verbose_name_plural': '일본 작품 태그 유형들',
            },
        ),
        migrations.AddField(
            model_name='japaneseworktag',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.japaneseworktagtype', verbose_name='유형'),
        ),
    ]
