# Generated by Django 5.2.3 on 2025-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_japaneseworktagtype_japaneseworktag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaneseworktag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
    ]
