# Generated by Django 5.2.3 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_japaneseworktag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanesePhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '일본 사진 태그',
                'verbose_name_plural': '일본 사진 태그들',
            },
        ),
        migrations.CreateModel(
            name='KoreanPhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '한국 사진 태그',
                'verbose_name_plural': '한국 사진 태그들',
            },
        ),
    ]
