# Generated by Django 5.2.3 on 2025-08-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_japanesephototag_koreanphototag'),
        ('persons', '0003_alter_japaneseactor_name_alter_koreanperson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanesePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='당시 연도')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(blank=True, to='persons.japaneseactor', verbose_name='출연 배우')),
                ('tags', models.ManyToManyField(blank=True, to='core.japanesephototag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '일본 사진',
                'verbose_name_plural': '일본 사진들',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JapanesePhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/japanese/')),
                ('photo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photos.japanesephoto')),
            ],
        ),
        migrations.CreateModel(
            name='KoreanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='당시 연도')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persons', models.ManyToManyField(blank=True, to='persons.koreanperson', verbose_name='출연 인물')),
                ('tags', models.ManyToManyField(blank=True, to='core.koreanphototag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '한국 사진',
                'verbose_name_plural': '한국 사진들',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KoreanPhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/korean/')),
                ('photo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photos.koreanphoto')),
            ],
        ),
    ]
