# Generated by Django 5.2.3 on 2025-07-02 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('other_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='다른 이름')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='출생연도')),
                ('debut_year', models.IntegerField(blank=True, null=True, verbose_name='데뷔연도')),
                ('looks', models.CharField(blank=True, max_length=3, null=True, verbose_name='외모')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='하드함')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actors/japanese_actors/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '일본 배우',
                'verbose_name_plural': '일본 배우들',
            },
        ),
        migrations.CreateModel(
            name='KoreanPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='출생연도')),
                ('looks', models.CharField(blank=True, max_length=3, null=True, verbose_name='외모')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='persons/korean_persons/', verbose_name='이미지')),
                ('tags', models.ManyToManyField(blank=True, to='core.koreanpersontag', verbose_name='태그 목록')),
            ],
            options={
                'verbose_name': '한국 인물',
                'verbose_name_plural': '한국 인물들',
            },
        ),
    ]
