# Generated by Django 5.2.3 on 2025-07-04 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_japaneseworktag_description'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koreanperson',
            options={'ordering': ['name'], 'verbose_name': '한국 인물', 'verbose_name_plural': '한국 인물들'},
        ),
        migrations.AddField(
            model_name='koreanperson',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='다른 이름'),
        ),
        migrations.AlterField(
            model_name='koreanperson',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='출생 연도'),
        ),
        migrations.AlterField(
            model_name='koreanperson',
            name='looks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='외모'),
        ),
        migrations.AlterField(
            model_name='koreanperson',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='koreanperson',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.koreanpersontag', verbose_name='태그'),
        ),
    ]
