# Generated by Django 5.2.3 on 2025-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_koreanperson_options_koreanperson_other_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japaneseactor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='koreanperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
