# Generated by Django 5.2.3 on 2025-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_japaneseactor_name_alter_koreanperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaneseactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='koreanperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
